name: rmgpgab-weatherman-europe-west1-Gigaton11-Weatherman--maktd
github:
  owner: Gigaton11
  name: Weatherman
  push:
    branch: ^main$
serviceAccount: projects/weatherman-492508/serviceAccounts/750230352076-compute@developer.gserviceaccount.com
build:
  options:
    logging: CLOUD_LOGGING_ONLY
  substitutions:
    _DEPLOY_REGION: europe-west1
    _SERVICE_NAME: weatherman
    _AR_HOSTNAME: europe-west1-docker.pkg.dev
    _AR_REPOSITORY: cloud-run-source-deploy
  steps:
    - name: gcr.io/cloud-builders/docker
      args:
        - build
        - -t
        - ${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}
        - .
    - name: gcr.io/cloud-builders/docker
      args:
        - push
        - ${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}
    - name: gcr.io/google.com/cloudsdktool/cloud-sdk
      entrypoint: gcloud
      args:
        - run
        - deploy
        - ${_SERVICE_NAME}
        - --image
        - ${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}
        - --region
        - ${_DEPLOY_REGION}
        - --platform
        - managed
        - --allow-unauthenticated
        - --quiet
  images:
    - ${_AR_HOSTNAME}/${PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:${SHORT_SHA}
